<?php
// Read the query parameters from the query string
parse_str($_SERVER['QUERY_STRING'], $queryParams);

// Extract the 'name' parameter from the query string
$name = isset($queryParams['name']) ? $queryParams['name'] : 'Guest';

// Generate the HTML response
$html = "<html>
<head>
<title>Greeting Page</title>
</head>
<body>
<h1>Welcome, $name!</h1>
<p>This is a dynamic greeting page generated by a CGI PHP script.</p>
</body>
</html>";

// Set the response headers
header("Content-type: text/html; charset=UTF-8");

// Print the HTML response
echo $html;
?>
